### ISSUE TITLE
Remove startup warning

### ISSUE THREAD

**Issue by HLeithner** [norganos/node-red-contrib-staircase-timer#2]
Hi, 

would be nice if you could remove this warning https://github.com/norganos/node-red-contrib-staircase-timer/blob/main/staircase-timer.js#L178

thanks

**Comment by norganos** [comment]
changed into a normal log message in release 1.0.3

**Comment by HLeithner** [comment]
thx

**Comment by Soundman71** [comment]
Hi,

can the log output also be removed? Otherwise it appears with every deploy of flows (in edit windows).

THX

**Comment by norganos** [comment]
do you mean all log outputs or just the startup message?
of course we could introduce a config option (e.g. "debug") which disables all logs.

**Comment by Soundman71** [comment]
Hi, I only mean the start message. Can't you use the debug node for this output? Stephan Linkel ***@***.***> schrieb am 6. Feb. 2024 um 15:00: do you mean all log outputs or just the startup message? of course we could introduce a config option (e.g. "debug") which disables all logs. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: ***@***.***>
